#!/bin/bash
### BEGIN INIT INFO
# Provides: omxplayer
### END INIT INFO

# Camera Feeds & Positions Quad
top_left="screen -dmS top_left sh -c 'omxplayer --win \"0 0 400 240\" "$2" -b --live; exec bash'"
top_right="screen -dmS top_right sh -c 'omxplayer --win \"400 0 800 240\" "$3" --live; exec bash'"
bot_left="screen -dmS bot_mid sh -c 'omxplayer --win \"0 240 400 480\" "$4" --live; exec bash'"
bot_right="screen -dmS bot_mid sh -c 'omxplayer --win \"400 240 800 480\" "$5" --live; exec bash'"
# Triple
main_left1="screen -dmS top_left sh -c 'omxplayer --win \"0 90 500 390\" "$2" -b --live; exec bash'"
top_right1="screen -dmS top_right sh -c 'omxplayer --win \"500 60 800 240\" "$3" --live; exec bash'"
bot_right1="screen -dmS bot_mid sh -c 'omxplayer --win \"500 240 800 420\" "$4" --live; exec bash'"
# Double1
left1="screen -dmS top_left sh -c 'omxplayer --win \"0 120 400 360\" "$2" -b --live; exec bash'"
right1="screen -dmS top_right sh -c 'omxplayer --win \"400 120 800 360\" "$3" --live; exec bash'"
# Double2
left2="screen -dmS top_left sh -c 'omxplayer --win \"0 120 400 360\" "$4" -b --live; exec bash'"
right2="screen -dmS top_right sh -c 'omxplayer --win \"400 120 800 360\" "$5" --live; exec bash'"
# Single
full_screen1="screen -dmS full_screen sh -c 'omxplayer --win \"0 0 800 480\" "$2" -b --live; exec bash'"

# Camera Feed Names
camera_feeds_quad=(top_left top_right bot_left bot_right)
camera_feeds_triple=(main_left1 top_right1 bot_right1)
camera_feeds_double1=(left1 right1)
camera_feeds_double2=(left2 right2)
camera_feeds_single1=(full_screen1)

# Assign cameras
case "$1" in
  cams4x)
    for i in "${camera_feeds_quad[@]}"
    do
    eval eval '$'$i
    done
    ;;
  cams3x)
    for i in "${camera_feeds_triple[@]}"
    do
    eval eval '$'$i
    done
    ;;
   cams2x1)
    for i in "${camera_feeds_double1[@]}"
    do
    eval eval '$'$i
    done
    ;;
  cams2x2)
    for i in "${camera_feeds_double2[@]}"
    do
    eval eval '$'$i
    done
    ;;
  camera1)
    for i in "${camera_feeds_single1[@]}"
    do
    eval eval '$'$i
    done
    ;;
  killall)
    sudo killall omxplayer.bin
    ;;

*)
exit 1
;;

esac
